### PR TITLE
updated/fixed test_vcf.vcf and bug report

### PR DESCRIPTION
**Pull request by dakl**
Hi Måns, 

I updated test_vcf.vcf in the following ways:

1. Fix missing newline for ##contig
2. Add explicit FORMAT tags for GT,GQ,AD and DP tags
3. Set DP_HIST to correct value(s). Number=R means one value per allele incl REF. 
4. Set fileformat to 4.2 (Number=R is a VCFv4.2 feature)
5. Removed TP from FORMAT which has no value fro mother or proband, and no corresponding `##FORMAT` in the header

This revealed a bug: The --split option does not split DP_HIST correctly (or at all it seems like): 

```
3	947379	.	A	T	100	PASS	MQ=1;CNT=5;DP_HIST=12,43,22	GT:GQ:AD:DP	1/1:60:0,7:12	0/0:60:7,0:17	0/1:60:0,7:16
3	947379	.	A	C	100	PASS	MQ=1;CNT=8;DP_HIST=12,43,22	GT:GQ:AD:DP	0/0:60:0,0:12	0/1:60:7,10:17	0/1:60:0,8:16
```

Being Number=R, it should have one value for each allele including ref (i.e. 3 values prior to split and 2 for biallelic variants). The code that splits INFO fields needs to check if they are `A`, `R` or `.`. 

Cheers =)

### CODE REVIEW

**Comment by moonso** [comment]
Hello,

Ok I thought R meant only one value for REF...
Then i will fix the correct split before merging this pull request.
For '.' it will probably not be possible to split in any smart way since we do not know if the values are associated with an allele or not, right?

**Comment by moonso** [comment]
It should split R-field proper noe.
Thank you for this one!

**Comment by dakl** [comment]
Thanks, will check it out tomorrow. I think the best behaviour for the
fields of type `.` is to pass them along as they are to each item in split
variants. I guess the alternative would be to drop them completely, which I
don't think makes sense.

cheers
Daniel

**Comment by dakl** [comment]
This works like a charm! Thanks for implementing!

**Pull request merged**
